### ISSUE TITLE
Bootstrap 3 changes

### ISSUE THREAD

**Issue by mrkre** [jdewit/bootstrap-timepicker#139]
Changes to input fields for Bootstrap 3, e.g. input-group class instead of input-append.

Also changes to how glyphicons are implemented. It is now a new repository.

**Comment by zervoulakus** [comment]
not working on bootstrap 3

**Comment by jesselathamdev** [comment]
+1 for Bootstrap 3 updates.

While #141 and #144 attempt to update certain components of the picker wrt glyphicons and input-group etc, I'm not sure how they address the "mobile first" aspect such as viewing on a mobile device and the control resizes (which I'm looking to support).

Cheers and hope to see an update or combintation of pull requests taken soon!

**Comment by nhoffmann** [comment]
Also +1 for Bootstrap 3 updates.

Or is there an official fork of this plugin that supports bootstrap 3.x already?

**Comment by jdewit** [comment]
Not that I know of. I don't currently need this myself and am tied up with other projects. Would welcome some help.

**Comment by canismarko** [comment]
For anyone interested, I forked and made a few simple changes to support bs3. Breaks backward-compatibility with 2.3.x so I didn't submit a pull request. I probably missed a lot but feel free to submit issues. No promises but I'll do my best to fix them. https://github.com/m3wolf/bootstrap3-timepicker

**Comment by LaurentSHB** [comment]
@m3wolf great job! 

@jdewit could you create a bootstrap3 branch in order to merge the pull-request of @m3wolf in? It would be great for your nice plugin!

**Comment by carpeliam** [comment]
@m3wolf Awesome work. I'm running into a bower issue with your fork, I can file an issue on your repo.

Personally what I'd most like to see is a semver approach of using @m3wolf's fork and incrementing the major release version, instead of having a separate branch/repo/whatever for BS2 and another for BS3. If this is versioned and issued as a PR to this repo, would that be accepted?

Edit: I see I can't file issues against @m3wolf's fork... yet another good reason, I think, to get his work merged in. The issue I'm running into is that the `bower.json` file hasn't been updated (either the version or the repo url), so even if I point it at your repo, it's still pointing at @jdewit as that's what's specified in your bower.json. In order to get it to work, I had to point it at a specific git commit, but this is weaksauce.

```
{
  // ...
  "dependencies": {
    "bootstrap": "~3.0.0",
    "bootstrap-timepicker": "https://github.com/m3wolf/bootstrap3-timepicker.git#f8910f47117f3822253ebaa4b0c1bb331aa649ba"
  }
}
```

**Comment by canismarko** [comment]
Thanks for the comment carpeliam. I'll take a look.

As I remember it, the issue was just one of adding the right class attributes for bootstrap 3. Maybe I can add the right ones for BS3 and BS2 so it's compatible with both. If I get that work I'll send a PR back to this repo.

**Comment by canismarko** [comment]
@carpeliam I updated the bower.json on my repo. Did I do it right? (full disclosure: this is my first experience with bower so it might be garbage). Issues should be enabled now, as well.

**Comment by carpeliam** [comment]
@m3wolf sorry for the late reply- out of the box, this tries to download https://github.com/m3wolf/bootstrap3-timepicker/archive/v0.2.6.tar.gz, which pulls from the right repo, but because the version number hasn't been incremented, presumably within bower.json, it's still pulling down the old version. Maybe changing the version to something like `0.2.6.m3wolf` might be appropriate? I'm not sure..

**Comment by mrhota** [comment]
Bootstrap 3 is now supported. Bootstrap 2 isn't. See PR #275. I think our changes here are even more complete than the various forks. Better late than never. :smile:
