### ISSUE TITLE
When reaching 00:00 on a 24hs timepicker, the input is cleared

### ISSUE THREAD

**Issue by denishavranek** [jdewit/bootstrap-timepicker#169]
I'm not sure if this is a good thing to do, as 00:00 is also a valid hour and in my case, I need to keep it so the user sees it. Shouldn't be this visibility issue configurable at least?

**Comment by chriswalkr** [comment]
+1

**Comment by aidenbell** [comment]
+1 for chriswalkr to fix

**Comment by manroalman** [comment]
+1

**Comment by hueitan** [comment]
+1
It should be optional for the user !!

**Comment by ghost** [comment]
@pgelinas

Pull Request #173: Removed usage of falsy value in if and prefer equality testing with empty string.

That didn't fix the issue. I have the latest version of bootstrap-timepicker (0.2.6 as of 2014-03-06), and I still have this issue of it not displaying when the time is 00:00

Can somebody please fix this? Or at least show me where in the code the cause might be, so that I can fix it myself. (I've been looking all day and I need this to work)

Edit: I apologize. It did fix the issue, but only if I use the non-minified version of the js file.

**Comment by Euregan** [comment]
So, this is still not working with the minified version, which I have to use, could you please fix it ?
Edit: Actually, scratch that, I'm using the non minified version 0.2.6

**Comment by mmarchini** [comment]
This issue seems to be fixed on version 0.5.1
