### ISSUE TITLE
Dropdown not working

### ISSUE THREAD

**Issue by cmckni3** [jdewit/bootstrap-timepicker#20]
I can't get the dropdown functionality to work. I am using bootstrap 2.0.3. I also tried in bootstrap 2.0.4. No luck. I tried with everything just like the documentation (copy, pasted source into file and changed bootstrap paths) but only the modal works.

Any ideas?

**Comment by oller** [comment]
Are you sure you are including the timepicker css styles? (from timepicker.less)

In installing this library, I noticed the beahviour you've described before I realized I hadn't included the necessary @import into my less file.

**Comment by cmckni3** [comment]
That's probably my issue. I didn't realize the stylesheet was only available as less. Should I have the less stylesheet converted to a normal one?

**Comment by oller** [comment]
You can do it that way, bootstrap itself uses .less - which I develop in and then have that compiled into css, so it was just a case of importing the timepicker.less into the list of less files I compile.

Give this a go - http://incident57.com/less/ (if you're on a mac - sure there's a pc equivalent) if you want to properly dive into less, otherwise it looks like you can convert the .less to .css at http://leafo.net/lessphp/#demo

**Comment by cmckni3** [comment]
Cool deal. I'm going to the Mac app. The php app is pretty cool too. Thanks

**Comment by nhodges** [comment]
This did the trick for me as well. Perhaps it should be made apparent that the CSS generated by the LESS document is required?

**Comment by cmckni3** [comment]
I agree with @nhodges

This issue can be closed (possibly after a response of whether the documentation was updated or won't be updated).

**Comment by jdewit** [comment]
I have included a compiled css file now for those that just want to drop it in.
