### ISSUE TITLE
Anyone want to take over this project?

### ISSUE THREAD

**Issue by jdewit** [jdewit/bootstrap-timepicker#225]
Anyone interested in commit access let me know! I just don't have the time to maintain it.

**Comment by tgirardi** [comment]
@jdewit, probably I could do it

**Comment by tgirardi** [comment]
@jdewit  What do you think are the most important milestones and issues to be solved for this project for the future months?

**Comment by jdewit** [comment]
Probably
1. Bootstrap 3 support. There is a fork somewhere where someone has done this.
2. Positioning. There are quite a few issues regarding the positioning of the dropdown/modal. 
3. Just staying on top of and closing issues.

**Comment by eleumik** [comment]
Hi, I would like to help for some parts since I would like to include this nice widget in a project as replacement for an existing one. I am focused on localization and integration with Java that I use to get localization info when the page is written and to parse the submitted text.  My aim would be to be able to use the control with any of the locale supported by java, in short the widget should be able to display and send back localized formats, (why send back ? to be consistent with the script-less version).  I pulled a first request for changing time separator and I would like to add also configurable AM / PM symbols and maybe AM/PM configurable position. An other feature I think nice is to use attributes on the HTML element to configure, I have seen a pull also for this.

**Comment by eleumik** [comment]
@tgirardi @jdewit  I made some changes that include merging some pull requests, some bug fixes and the configurable localization support I wrote up, almost reached full support for localization, taken care default behavior was same as before. Please take in consideration this and let me know if we can merge. thanks. 

https://github.com/eleumik/bootstrap-timepicker/commits/gh-pages/js/bootstrap-timepicker.js

**Comment by Robelind** [comment]
The Bootstrap 3 fork is here: https://github.com/rendom/bootstrap-3-timepicker
Would be great if that project could be merged into this one.

**Comment by tgirardi** [comment]
Thanks @Robelind for the info.

I'm planning on taking the following roadmap:
1. Solving the most important issues of the current version
2. Accepting PR's that contains significant improvements to the current version
3. Release a new version including 1 and 2
4. Adding Bootstrap 3 support

I think it would be better to solve the current issues before making a big change (for what I've seen, Bootstrap 3 is pretty different from Bootstrap 2).

Anyone interested in helping me by taking care of some of the open issues (specially those related with Bugs)?

**Comment by brad** [comment]
@Robelind is the Bootstrap 3 version backwards compatible with Bootstrap 2?

**Comment by dozoisch** [comment]
@brad nope it's not

**Comment by mrhota** [comment]
The plugin is now being maintained and improved by me and @mmarchini
