### ISSUE TITLE
Unable to close dropdown when click on other input fields

### ISSUE THREAD

**Issue by greatghoul** [jdewit/bootstrap-timepicker#23]
1. Instance the timepicker on input field A
2. Click on A to show dropdown
3. click on another input field B

timepicker dropdown will no hide.

Please help.

**Comment by jdewit** [comment]
this has been fixed

**Comment by Diolor** [comment]
Though it should work, unfortunately it partially does. 

I believe that you have made it when there is a click away to close. I am using:

```
 <div ><input type="text" class="timepicker-default input-small"></div>
 $('.timepicker-default').timepicker();
```

In my script I'm creating some input fields with jquery which when I click them the timepicker doesn't close and I see the bootstrap's focus blue border. Nevertheless when I click on a previously created input e.g. searchbar the timepicker closes.

So the bug might be fixed by instead of clicking away, to have a while input is active to be visible.

Update: I also have a .on() event on the area that cannot be closed. That might help
