### ISSUE TITLE
Is there a CSS file for this, seems to be missing

### ISSUE THREAD

**Issue by BrewDawg** [jdewit/bootstrap-timepicker#302]
The demo includes it, but it's not there

**Comment by MrGeneric** [comment]
Its included in the download zip. 

https://github.com/jdewit/bootstrap-timepicker/releases

**Comment by mrhota** [comment]
Yes, you can clone the repo and build the project which will produce minified js and css files, or you can download one of the official zipped releases. Does that help? Shall I close this?

Thank you, @MrGeneric.

**Comment by jaapz** [comment]
For use with npm it would be greatly appreciated if you provide a dist/ directory containing minified versions of both the javascript and the compiled css. That makes including this in applications way less complicated

**Comment by mrhota** [comment]
see #301. Build artifacts do not belong in version control. I know next to nothing about npm. Can it not download release archives attached to a version tag? If not, I'd say that's worthy of an NPM feature request.

If you know of some alterations I can make to the package.json file to make this easier on people, I'm happy to accept a PR.

**Comment by jaapz** [comment]
For a package to exist on npm, you don't need to have build artifacts in your source control. You can simply build the artifacts locally, and then run `npm publish`. The npm tool will then also push the build artifacts to the npm registry. This is basically the same as creating a release tar file, with the extra benefit of it being on a package registry used by lots and lots of people.

Npm can also install tar files directly, but only if they have a `package.json` file in it, which describes the package and it's important files. Also I am not sure it could actually install the release tarfiles provided with this project because they are released as [tarbombs](https://en.wikipedia.org/wiki/Tar_%28computing%29#Tarbomb).

**Comment by mrhota** [comment]
Yikes! Thanks for the tarbomb info. I messed that up.

**Comment by mrhota** [comment]
@jaapz is there anything special I need to do before I run `npm publish`? Do I need an npm account or something?

**Comment by mrhota** [comment]
I updated the v0.5.0 and v0.5.1 releases with tarballs instead of tarbombs. The .tar.gz and .zip files contain `package.json`.

**Comment by jaapz** [comment]
@mrhota great! I think the only thing you need to do to publish is to create a user on npmjs.org. Afaik the `npm publish` command should guide you through the process.

You should make sure that the correct files are pushed to the registery, this is the documentation about that: https://docs.npmjs.com/files/package.json#files

If you need any help with this don't hesitate to ask then we can look at it together.

**Comment by mrhota** [comment]
OK, I screwed up the npm stuff since someone else had published this project first. He has since unpublished it, but it necessitated a version bump from v0.2.6 -> v0.2.7 before I could publish what is essentially that same version. I also published v0.3.0, v0.5.0, and v0.5.1. Release tags back to v0.2.6 also have release tarballs and zips attached to them.

I'm closing this for now.

**Comment by mrhota** [comment]
See #310 for my NPM screw-up.

**Comment by jaapz** [comment]
@mrhota thanks for the npm publish, I am using version 0.5.1 now and it's working fine!

**Comment by jaapz** [comment]
@mrhota scratch my previous comment, it looks like the built files are not yet up on npm. Could you make sure the built css is correctly pushed to npm and the "main" field is correctly set in the package.json? The 0.5.1 version on npm currently does not have both.

**Comment by jaapz** [comment]
Looks like `npm publish` does not push files that are in .gitignore. So that's probably why all build artifacts are not on npm yet?

**Comment by mrhota** [comment]
if you know how package.json should be changed, a PR would be appreciated.
I don't have much patience for npm of late.

**Comment by jaapz** [comment]
@mrhota no problem, I will check it out and submit a PR :)
